### ISSUE TITLE
Big Suggestion: record and stream audio to server, and do mixing and de-reverberation on server side

### ISSUE THREAD

**Issue by xuancong84** [bhj/karaoke-forever#19]
HTML5 now support streaming live audio/video. You can use the technique in https://www.html5rocks.com/en/tutorials/getusermedia/intro/ to allow each user to turn on their phone microphone and stream live audio to server. Then on the server side, you can do some signal processing to mix the MTV audio with each user's singing voice with de-reverberation, after which the mixed audio data is streamed to the player for playback. Then, we truly have a Home Karaoke system -:)

**Comment by bhj** [comment]
PRs accepted ;)

**Comment by xuancong84** [comment]
Sorry, I accidentally created 2 identical issues, because Github has bugged out (404 error when I click "submit new issue" but the issue has been created successfully). And I cannot delete the erroneously created issue. So please reply in the open issue on this topic. Thanks!
