### ISSUE TITLE
Organized by title

### ISSUE THREAD

**Issue by viperxx01** [bhj/karaoke-forever#28]
can i get a code that can organized by title, like it can show all any song that starts with A, and then if i scroll down until the last song at A, it will show all song starts with B. then if i scroll up again it will back to A. so it will not show all songs. pls help me ty.

**Comment by bhj** [comment]
Hi @viperxx01, if I understand correctly you would like songs grouped by title rather than artist, and to only see one letter group at a time? That's not currently possible but it's an interesting request. Can you elaborate on your use case for this?
